# -*- coding: utf-8 -*-
"""DistilBERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBHj3CY1ZVtWuLjNsU1lP1JzhOLGa0J6

**AI Content Detection Using DistilBERT**
"""

import pandas as pd

DATA_PATH = "/content/drive/MyDrive/Training_Essay_Data.csv"

df = pd.read_csv(DATA_PATH)

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nLabel distribution (generated):")
print(df["generated"].value_counts(dropna=False))

df.sample(3, random_state=42)

from sklearn.model_selection import train_test_split
import re

has_missing = df.isnull().values.any()
print(df.isnull().sum())

print(df.columns)

df2 = df[["text", "generated"]].dropna().copy()
df2["text"] = df2["text"].astype(str)
df2["generated"] = df2["generated"].astype(int)

def clean_text_minimal(s: str) -> str:
    s = s.replace("\r", " ").replace("\n", " ")
    s = re.sub(r"\s+", " ", s).strip()
    return s

df2["text"] = df2["text"].apply(clean_text_minimal)

print("After cleaning:", df2.shape)
print("Label distribution:\n", df2["generated"].value_counts())

train_df, temp_df = train_test_split(
    df2,
    test_size=0.30,
    random_state=42,
    stratify=df2["generated"]
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42,
    stratify=temp_df["generated"]
)

print("\nSplit sizes:")
print("Train:", train_df.shape)
print("Val  :", val_df.shape)
print("Test :", test_df.shape)

print("\nTrain label distribution:\n", train_df["generated"].value_counts(normalize=True))
print("\nVal label distribution:\n", val_df["generated"].value_counts(normalize=True))
print("\nTest label distribution:\n", test_df["generated"].value_counts(normalize=True))

from datasets import Dataset
from transformers import AutoTokenizer

MODEL_NAME = "distilbert-base-uncased"
MAX_LEN = 512

train_ds = Dataset.from_pandas(train_df.reset_index(drop=True))
val_ds   = Dataset.from_pandas(val_df.reset_index(drop=True))
test_ds  = Dataset.from_pandas(test_df.reset_index(drop=True))

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

def tokenize_fn(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        max_length=MAX_LEN
    )
train_tok = train_ds.map(tokenize_fn, batched=True, remove_columns=["text"])
val_tok   = val_ds.map(tokenize_fn, batched=True, remove_columns=["text"])
test_tok  = test_ds.map(tokenize_fn, batched=True, remove_columns=["text"])

train_tok = train_tok.rename_column("generated", "labels")
val_tok   = val_tok.rename_column("generated", "labels")
test_tok  = test_tok.rename_column("generated", "labels")

cols = ["input_ids", "attention_mask", "labels"]
train_tok.set_format(type="torch", columns=cols)
val_tok.set_format(type="torch", columns=cols)
test_tok.set_format(type="torch", columns=cols)

print("Tokenized columns:", train_tok.column_names)
print("One sample keys:", train_tok[0].keys())
print("input_ids length:", len(train_tok[0]["input_ids"]))
print("labels example:", train_tok[0]["labels"])

from transformers import AutoModelForSequenceClassification

NUM_LABELS = 2

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=NUM_LABELS
)

model

import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="binary"
    )
    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./distilbert_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    fp16=True,
    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tok,
    eval_dataset=val_tok,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

trainer.train()

test_results = trainer.evaluate(test_tok)
print("Test Results:", test_results)

pred_output = trainer.predict(test_tok)
logits = pred_output.predictions
y_true = pred_output.label_ids
y_pred = np.argmax(logits, axis=1)

print("y_true shape:", y_true.shape)
print("y_pred shape:", y_pred.shape)

from sklearn.metrics import classification_report, confusion_matrix

target_names = ["Human (0)", "AI (1)"]

print(classification_report(y_true, y_pred, target_names=target_names, digits=4))

cm = confusion_matrix(y_true, y_pred)
print("Confusion Matrix:\n", cm)

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(5, 4))
plt.imshow(cm)
plt.title("Confusion Matrix (DistilBERT, Test Set)")
plt.xticks([0, 1], ["Human", "AI"])
plt.yticks([0, 1], ["Human", "AI"])
plt.xlabel("Predicted")
plt.ylabel("Actual")

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, str(cm[i, j]), ha="center", va="center")

plt.colorbar()
plt.show()

log_history = trainer.state.log_history

train_loss = [entry["loss"] for entry in log_history if "loss" in entry]
eval_loss  = [entry["eval_loss"] for entry in log_history if "eval_loss" in entry]
eval_acc   = [entry["eval_accuracy"] for entry in log_history if "eval_accuracy" in entry]

epochs = list(range(1, len(eval_loss) + 1))

plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.plot(epochs, train_loss[:len(epochs)], label="Training Loss")
plt.plot(epochs, eval_loss, label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("DistilBERT: Loss vs Epoch")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(epochs, eval_acc, marker="o", color="red", label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("DistilBERT: Accuracy vs Epoch")
plt.legend()

plt.tight_layout()
plt.show()